[package]
name = "dns-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
props-rs = "0.1.0"
serde_json = "1.0"
regex = "1.1.9"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"], default-features = false }
